### ISSUE TITLE
Loading for SPA-style AJAX sites

### ISSUE THREAD

**Issue by TheFunkyMonk** [matt-west/craft-recaptcha#19]
I'm using [Barba.js](https://barba.js.org/docs/getstarted/intro/) to load pages via AJAX for page transitions, and when my contact page is navigated to in this way, loading the ReCaptcha via `{{ craft.recaptcha.render() }}` (expectedly) doesn't show up.

Often with plugins like this, there's some sort of script block injected into the template I can run `eval` on after my page transition, but it appears the `render()` method just outputs an empty div with `id=gRecaptchaContainer` in this case.

Is there a window method I can call after page transition to kick off the needed functionality? Or any other suggestions you might have?

**Comment by matt-west** [comment]
I don’t have any experience with Barba.js, but this issue is likely that the recaptcha script isn’t being loaded. We register the file with Craft which is then responsible for inserting it into pages where `{{ craft.recaptcha.render() }} ` has been called.

Try these instructions for explicitly loading the reCAPTCHA instead:
https://developers.google.com/recaptcha/docs/display#explicitly_render_the_recaptcha_widget
